config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: 'homes#top'
  resources :users, only: [:index, :show, :edit,:update]
  resources :pettys,only:[:index,:show,:new,:edit,:create,:update,:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/petty.rb
class Petty < ApplicationRecord
  belongs_to :user
  validates :category, presence: true
  validates :day, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pettys, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top] # top アクションのみログインしアクセス可能にする
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/pettys_controller.rb
class PettysController < ApplicationController
  def new
    @petty = Petty.new
  end

  def create
    @petty = Petty.new(petty_params)
    @petty.user_id = current_user.id
    @petty.total_money = @petty.money_1 + @petty.money_2 + @petty.money_3
    if @petty.save
      flash[:notice] = '正常に登録できました'
      redirect_to petty_path(@petty.id)
    else
      render :new
    end
  end

  def index
    @pettys = Petty.all

  end

  def show
    @petty = Petty.find(params[:id])
  end

  def edit
    @petty = Petty.find(params[:id])
  end

  def update
    @petty = Petty.find(params[:id])
    @petty.update(update_petty_params)
    @petty.total_money = @petty.money_1 + @petty.money_2 + @petty.money_3
    if @petty.save
      flash[:notice] = '変更できました'
      redirect_to petty_path(@petty.id)
    else
      render :edit
    end
  end

  def destroy
    @petty = Petty.find(params[:id])
    @petty.destroy
    redirect_to user_path(current_user.id)
  end

  private

  def petty_params
    params.require(:petty).permit(:category,:day,:breakdown_1,:breakdown_2,:breakdown_3,:money_1,:money_2,:money_3)
  end

  def update_petty_params
    params.require(:petty).permit(:category,:day,:breakdown_1,:breakdown_2,:breakdown_3,:money_1,:money_2,:money_3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @pettys = Petty.all
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name,:section,:password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pettys_helper.rb
module PettysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<main class="bg-light">
  <p id="notice"><%= flash[:notice] %></p>
  <div class="h-100 mt-5 pt-5 pb-5">
  <div class="container">
    <div class="row">
      
      <div class="mx-auto pt-5">
        <h1 class="display-4 text-secondary">小口管理システム</h1>
        <p>小口管理システムのメリット</p>
        <ul>
          <li>手入力作業ならではの入力漏れは無し</li>
          <li>電卓も不要</li>
        </ul>　
        <h3 class="pt-5 text-danger">エクセル管理からもう脱出しましょう！</h3>
        　<div class="btn-wrapper col-10 mx-auto pb-5">
            <div class="row">
              <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">ログイン</a>
            </div>
            <div class="row">
              <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">新規登録</a>
            </div>
        　</div>
      </div>
    </div>
  </div>
 </div>
</main>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-white bg-white">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span class="text-warning">Top画面へ</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li>
            <a class="nav-link text-secondary" href="/pettys/new">
              伝票入力
            </a>
          </li>
          <li>
            <a class="nav-link text-secondary" href="/users/<%= current_user.id %>">
              マイページ
            </a>
          </li>
          <li>
            <a class="nav-link text-secondary" href=" /pettys">
              伝票一覧
            </a>
          </li>
          <li>
            <a class="nav-link text-secondary" rel="nofollow" data-method="delete" href="/users/sign_out">
              <i class="fas fa-sign-out-alt"></i>Log out
            </a>
          </li>
          <% else %>
          <li>
            <a class="nav-link text-secondary" href="/users/sign_up">
              <i class="fas fa-user-plus"></i>新規登録
            </a>
          </li>
          <li>
            <a class="nav-link text-secondary" href="/users/sign_in">
              <i class="fas fa-sign-in-alt"></i>ログイン
            </a>
          </li>
           <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Accounting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
    <div class="flash">
       <h2 class="text-success"><%= flash[:notice] %></h2>
    </div>
    <% end %>
    <%= render 'layouts/header' %>
    
    <%= yield %>
  </body>
</html>

app/views/pettys/_list.html.erb
<%= form_with model:@petty,url:pettys_path,local:true do |f| %>
  <h4>経費選択</h4>
  <p><%= f.text_field:category %></p>
  <h4>日付</h4>
  <p><%= f.date_field:day %></p><br>
  <p>
    明細1:<%= f.text_field:breakdown_1 %>
    明細1の金額:<%= f.number_field:money_1,value:0,required: true %>
  </p>
  <p>
    明細2:<%= f.text_field:breakdown_2 %>
    明細2の金額:<%= f.number_field:money_2,value:0,required: true %>
  </p>
  <p>
    明細3:<%= f.text_field:breakdown_3 %>
    明細3の金額:<%= f.number_field:money_3,value:0,required: true %>
  </p><br>
  <%= f.submit '登録' %>
<% end %>

app/views/pettys/edit.html.erb
<h1>伝票編集入力</h1>

<% if @petty.errors.any? %>
  <p class="text-danger"><%= @petty.errors.count %>件のエラーが発生しました</p>
  <ul>
  <% @petty.errors.full_messages.each do |message| %>
    <li>
      <p class="text-danger"><%= message %></p>
    </li>
  <% end %>
  </ul>
<% end %>

<%= form_with model:@petty,url:petty_path,local:true do |f| %>
  <h4>経費選択</h4>
  <p><%= f.text_field:category %></p>
  <h4>日付</h4>
  <p><%= f.date_field:day %></p><br>
  <p>
    明細1:<%= f.text_field:breakdown_1 %>
    明細1の金額:<%= f.number_field:money_1,value:0,required: true %>
  </p>
  <p>
    明細2:<%= f.text_field:breakdown_2 %>
    明細2の金額:<%= f.number_field:money_2,value:0,required: true %>
  </p>
  <p>
    明細3:<%= f.text_field:breakdown_3 %>
    明細3の金額:<%= f.number_field:money_3,value:0,required: true %>
  </p><br>
  <%= f.submit '登録' %><br><br>
  <%= link_to '戻る',petty_path(@petty) %>
<% end %>

app/views/pettys/index.html.erb
<div class="container">
  <div class="row mx-auto">
    <div class="col-lg-1"></div>
      <div class="col-lg-8">
        <h3>伝票一覧</h3>
       <table class='table table-hover table-inverse'>
         <thead>
           <tr>
             <th>申請者</th>
             <th>日付</th>
             <th>経費</th>
             <th>金額</th>
           </tr>
         </thead>
         <tbody>
         <% @pettys.each do |petty|%>
            <tr>
               <td><%= petty.user.name %></td>
               <td><%= petty.day %></td>
               <td><%= petty.category %></td>
               <td><%= petty.total_money %></td>
           </tr>
         <% end %>
         </tbody>
       </table>
     </div>  
     <div class="col-lg-1"></div>
   </div>
</div>

app/views/pettys/new.html.erb
<h1>伝票新規入力</h1>

<% if @petty.errors.any? %>
  <p class="text-danger"><%= @petty.errors.count %>件のエラーが発生しました</p>
  <ul>
  <% @petty.errors.full_messages.each do |message| %>
    <li>
      <p class="text-danger"><%= message %></p>
    </li>
  <% end %>
  </ul>
<% end %>

<%= render 'pettys/list' %>

app/views/pettys/show.html.erb
<div class="container"> 
 <div class="row">
  <div class="col-lg-2"></div>
    <div class="col-lg-8">
      <h2>出金伝票</h2>
      <%= @petty.day %>
      <table class='table table-hover table-inverse'>
      <thead>
       <tr class="table table-borderless">
         <td></td>
         <td>申請者名</td>
         <td><%= current_user.name %></td>
       </tr>
       <tr class="table table-borderless" >
         <td></td>
         <td>配属部署</td>
         <td><%= current_user.section %></td>
       </tr>
       <tr class="table table-bordered">
         <th>勘定科目</th>
         <th>摘要</th>
         <th>金額</th>
      
       </tr>
     </thead>
     <tbody class="table table-bordered">
         <tr>
           <td><%= @petty.category %></td>
           <td><%= @petty.breakdown_1 %></td>
           <td><%= @petty.money_1 %></td>
         </tr>
         <tr>
           <td><%= @petty.category %></td>
           <td><%= @petty.breakdown_2 %></td>
           <td><%= @petty.money_2 %></td>
         </tr>  
         <tr>
           <td><%= @petty.category %></td>
           <td><%= @petty.breakdown_3 %></td>
           <td><%= @petty.money_3 %></td>
         </tr>
         <tr>
           <td>仮払消費税等</td>
           <td></td>
           <td></td>
         </tr>
         <tr>
           <td>合計</td>
           <th></td>
           <td><%= @petty.total_money %></td>
         </tr>
      </tbody>
     </table>
     <%= link_to '編集',edit_petty_path(@petty.id),class:"btn btn-outline-warning"%>
     <%= link_to '削除',petty_path(@petty.id),method: :delete, "data-confirm" => "本当に削除しますか？",class:"btn btn-outline-warning" %>
     <%= link_to '戻る',user_path(current_user.id) %>
    </div>
    <div class="col-lg-2"></div>
 </div>
</div>

app/views/users/edit.html.erb
<h2>登録変更</h2>
<%= form_with model:@user,local:true do |f| %>
  <h4>名前</h4>
  <p><%= f.text_field:name %></p>
  <h4>パスワード</h4>
  <p><%= f.text_field:password %></p><br>
  </p><br>
  <p><%= f.text_field:section %></p><br>
  </p><br>
  <%= f.submit '登録変更' %>
<% end %> 

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class=container>
  <div class="row">
    <div class="col-lg-3">
       <h2>ユーザー情報</h2>
       <p>ユーザー名:<%= @user.name %></p>
       <%= link_to 'ユーザー情報変更',edit_user_path(@user),class:"btn btn-secondary" %>
    </div>
    <div class="col-lg-1"></div>

    <div class="col-lg-8">
     <h2>伝票一覧</h2>
     <table class='table table-hover table-inverse'>
      <thead>
       <tr>
         <th>申請者</th>
         <th>日付</th>
         <th>経費</th>
         <th>金額</th>
       </tr>
     </thead>
     <tbody>
      <% @user.pettys.each do |petty|%>
         <tr>
           <td><%= petty.user.name %></td>
           <td><%= petty.day %></td>
           <td><%= petty.category %></td>
           <td><%= petty.total_money %></td>
           <td><%= link_to '伝票画面へ',petty_path(petty.id),class:"btn btn-info"%></td>
         </tr>
      <% end %>
      </tbody>
    </table>
  </div>
 </div>
</div>